# Generated by Django 2.2 on 2023-08-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0006_auto_20230820_2130'),
        ('votaciones', '0006_auto_20230820_2119'),
    ]

    operations = [
    ]
