# Generated by Django 2.2 on 2023-08-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0007_merge_20230823_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotostest',
            name='fecha_voto_act',
            field=models.CharField(default='23/08/2023', max_length=120),
        ),
        migrations.AddField(
            model_name='registrovotostest',
            name='hora_voto_act',
            field=models.CharField(default='-', max_length=120),
        ),      
    ]
