# Generated by Django 2.2 on 2023-09-21 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0011_auto_20230824_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovotostest',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovotostest',
            name='ip_votante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovotostest',
            name='nombre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='categoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='link_facebook',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='link_instagram',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='link_video',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='pagina_web',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vinnastest',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votaciones.RegionesTest'),
        ),
    ]
